[package]
name = "stensor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
len-trait = "0.6.1"
num-traits = "0.2.15"
array-init = "2.0.1"